---
language: ruby
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.8
  - 2.4.5
  - 2.5.3
script:
  - bundle exec rake spec
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: "krpHaZ5Un9MH2Qz9VlRe/mQsipL9GTtgm/Q6dHtQKjKmNZljSaYFOXcK9NtQXfVs7rrTCuhYLlGnX3U5LbFfsLSPEeCy6S2lK486a9gN1xsp4zCimuv80Nmt+CJtQ03f0v+lK7U/SxFYihjn/lTzfgkEO1/oasNzLUapojAVK40WlmrEgAECHqDUQOxmaD9sRK8PJg3sRoYf+9M/UwTZm1kW2w9yphu5hOAL1dl/VU2JVLPe0ytYLt4/BaDXWuml9zC5Z/6trm7zyWZ6kcgcBGg28+T074b6RO3DNezCuA3Q56fI4ToOF7W3IZ1h9STx7m71Og3mK7YPw/mP0p8gT5yL6laqY1WjMQDbJLLomys0e9fmb3zg65BC9mlKIrrk42rK7ShbnFy3hfWlWqo+3SMej7hzE78PjkZm63mmpwV4gIrc6+ps4AUnY9rfL9Bdl/tbD4GhYI4Pms2PMwJqYkhV6IOzjjJwhcVcYaeIrQeIW3LWuBluNLLd1i8FP2jtDEL6KSgATt5KEDtRm1ns+eNv3LN/Cet6HQwIKWzfYEC5th0wKcYwg9h5A7XJ+XvFTU/NhibfGBF1xgI3d8BAQ/GKc5O44mMQlgTOjN4VD0GUUuANtAwtYuy+ii5FTlyS+L8l3UKlQ5yPS64+JnX2ZadSNuvgVTjfvSQX1Q7BAxI="
  on:
    rvm: 2.0.0
    tags: true
